const teamData = [
    {id: '1',
     name: 'The A-Team',
     members: [
      {id: 1,
       name: 'Jonathan Richardson',
       email: 'jrichardson@myeamil.com',
       role: 'Front-End Developer'},
      {id: 2,
       name: 'Harry Potter',
       email: 'hpotter@myeamil.com',
       role: 'Master of Disguise'},
      {id: 3,
       name: 'Ron Weasley',
       email: 'Rweasley@myeamil.com',
       role: 'Master of Persuasion'},
      {id: 4,
       name: 'Albus Dumbledore',
       email: 'ADumbledore@myeamil.com',
       role: 'Muscle'},
      {id: 5,
       name: 'Hermione Granger',
       email: 'hgranger@myeamil.com',
       role: 'The Brains'}]},
     {id: '2',
      name: 'TKO',
      members: [
       {id: 1,
        name: 'Jonathan Richardson',
        email: 'jrichardson@myeamil.com',
        role: 'Front-End Developer'},
       {id: 2,
        name: 'Minerva McGonagall',
        email: 'Mmcgongall@myeamil.com',
        role: 'Master Teacher'},
       {id: 3,
        name: 'Lord Voldemort',
        email: 'LVoldemort@myeamil.com',
        role: 'Master of Dark Arts'}]},
  ];
  
  export default teamData;